name: Audit live site
on: pull_request

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Audit live URL
        uses: jakejarvis/lighthouse-action@master
        with:
          netlify_site: 'stupefied-lamarr-d9f281.netlify.app'
      - uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'
